ARG BUILDPLATFORM
FROM --platform=${BUILDPLATFORM} golang:1.25-alpine AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETARCH=arm64
ARG VERSION=dev
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build \
    -ldflags "-s -w -X main.Version=${VERSION}" \
    -o /out/moodle-lambda ./cmd/moodle-lambda

FROM public.ecr.aws/awsguru/aws-lambda-adapter:1.0.1 AS adapter

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=adapter /lambda-adapter /opt/extensions/lambda-adapter
COPY --from=build /out/moodle-lambda /usr/local/bin/moodle-lambda

ENV AWS_LWA_PORT=8080 \
    AWS_LWA_READINESS_CHECK_PATH=/healthz \
    AWS_LWA_READINESS_CHECK_HEALTHY_STATUS=200 \
    AWS_LWA_INVOKE_MODE=response_stream

EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/moodle-lambda"]
